services:
  order-service:
    container_name: bidmart-order-app
    image: mugmold/bidmart-order:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8086"
    env_file:
      - .env
    environment:
      SERVICE_TOKEN: ${SERVICE_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      BIDDING_SERVICE_URL: ${BIDDING_SERVICE_URL}
      CATALOG_SERVICE_URL: ${CATALOG_SERVICE_URL}
      WALLET_SERVICE_URL: ${WALLET_SERVICE_URL}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped
